### ISSUE TITLE
repo steps with claude2-1 does not work

### ISSUE THREAD

**Issue by iitrsamrat** [gkamradt/LLMTest_NeedleInAHaystack#43]
steps to reproduce
pip install needlehaystack
`
needlehaystack.run_test --provider anthropic --model_name "claude-2.1" --document_depth_percents "[50]" --context_lengths "[2000]"
/Users/samsaha2/miniconda3/envs/nih/lib/python3.9/site-packages/langchain/callbacks/__init__.py:37: LangChainDeprecationWarning: Importing this callback from langchain is deprecated. Importing it from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.callbacks import base`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/samsaha2/miniconda3/envs/nih/bin/needlehaystack.run_test", line 5, in <module>
    from needlehaystack.run import main
  File "/Users/samsaha2/miniconda3/envs/nih/lib/python3.9/site-packages/needlehaystack/__init__.py", line 1, in <module>
    from .llm_needle_haystack_tester import LLMNeedleHaystackTester
  File "/Users/samsaha2/miniconda3/envs/nih/lib/python3.9/site-packages/needlehaystack/llm_needle_haystack_tester.py", line 10, in <module>
    from .providers import ModelProvider
  File "/Users/samsaha2/miniconda3/envs/nih/lib/python3.9/site-packages/needlehaystack/providers/__init__.py", line 1, in <module>
    from .anthropic import Anthropic
  File "/Users/samsaha2/miniconda3/envs/nih/lib/python3.9/site-packages/needlehaystack/providers/anthropic.py", line 12, in <module>
    from .model import ModelProvider
  File "/Users/samsaha2/miniconda3/envs/nih/lib/python3.9/site-packages/needlehaystack/providers/model.py", line 5, in <module>
    class ModelProvider(ABC):
  File "/Users/samsaha2/miniconda3/envs/nih/lib/python3.9/site-packages/needlehaystack/providers/model.py", line 10, in ModelProvider
    def generate_prompt(self, context: str, retrieval_question: str) -> str | list[dict[str, str]]: ...
TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'

`

`
running pip install -U langchain-community create conflict

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
needlehaystack 0.1.0 requires langchain-core==0.1.26, but you have langchain-core 0.1.36 which is incompatible.

`

**Comment by iitrsamrat** [comment]
`
with python 3.12.1 failed to install requirements

Building wheels for collected packages: multidict
  Building wheel for multidict (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for multidict (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [200 lines of output]
      *********************


`

**Comment by Ashh-Z** [comment]
Was able to set it up with a lower python environment (<3.10)
